services:
  app:
    build: ./app/
    ports:
      - 5000:5000
    depends_on:
      - mysql
  mysql:
    build: ./sql/
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"